// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Pages = Collections['pages']['schema']['_output']
export declare const pages: Pages[]

export type Writing = Collections['writing']['schema']['_output']
export declare const writing: Writing[]
