import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";
import path from "path";
import { PostFilePaths, PostsPath } from "../../mdx/mdx-paths";

export default function Index({ posts }) {
  return (
    <div>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/blog/${post.filePath.replace(/\.mdx?$/, "")}`}
              href={`/blog/[slug]`}
            >
              {post.data.title}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

export function getStaticProps() {
  const posts = PostFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(PostsPath, filePath));
    const { content, data } = matter(source);

    return {
      content,
      data,
      filePath,
    };
  });

  return { props: { posts } };
}
